---
- name: Install RabbitMQ
  apt:
    name: rabbitmq-server
    state: latest

- name: Enable Consul discovery in RabbitMQ
  command: "rabbitmq-plugins --offline enable rabbitmq_peer_discovery_consul"
  when: runtime

- name: Create /etc/rabbitmq/rabbitmq.conf
  template:
    src: templates/rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
  when: runtime

- name: Ensure RabbitMQ is restarted
  service:
    name: rabbitmq-server
    state: restarted
