---
- name: Ensure PostgreSQL packages are installed.
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
    state: present

- name: Configure client auth
  copy:
    src: files/pg_hba.conf
    dest: /etc/postgresql/11/main/pg_hba.conf
